// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import (
	idfy "bitbucket.org/junglee_games/getsetgo/sdks/idfy"
	mock "github.com/stretchr/testify/mock"
)

// Idfy is an autogenerated mock type for the Idfy type
type Idfy struct {
	mock.Mock
}

// CheckTemperedImage provides a mock function with given fields: req
func (_m *Idfy) CheckTemperedImage(req idfy.CheckTemperedReq) (bool, error) {
	ret := _m.Called(req)

	var r0 bool
	if rf, ok := ret.Get(0).(func(idfy.CheckTemperedReq) bool); ok {
		r0 = rf(req)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(idfy.CheckTemperedReq) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ExtractAadhar provides a mock function with given fields: idfyrequest
func (_m *Idfy) ExtractAadhar(idfyrequest idfy.IdfyRequest) (*idfy.IdfyAadharResponse, error) {
	ret := _m.Called(idfyrequest)

	var r0 *idfy.IdfyAadharResponse
	if rf, ok := ret.Get(0).(func(idfy.IdfyRequest) *idfy.IdfyAadharResponse); ok {
		r0 = rf(idfyrequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*idfy.IdfyAadharResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(idfy.IdfyRequest) error); ok {
		r1 = rf(idfyrequest)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ExtractDl provides a mock function with given fields: idfyrequest
func (_m *Idfy) ExtractDl(idfyrequest idfy.IdfyRequest) (*idfy.IdfyDlResponse, error) {
	ret := _m.Called(idfyrequest)

	var r0 *idfy.IdfyDlResponse
	if rf, ok := ret.Get(0).(func(idfy.IdfyRequest) *idfy.IdfyDlResponse); ok {
		r0 = rf(idfyrequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*idfy.IdfyDlResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(idfy.IdfyRequest) error); ok {
		r1 = rf(idfyrequest)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ExtractPan provides a mock function with given fields: idfyrequest
func (_m *Idfy) ExtractPan(idfyrequest idfy.IdfyRequest) (*idfy.IdfyPanResponse, error) {
	ret := _m.Called(idfyrequest)

	var r0 *idfy.IdfyPanResponse
	if rf, ok := ret.Get(0).(func(idfy.IdfyRequest) *idfy.IdfyPanResponse); ok {
		r0 = rf(idfyrequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*idfy.IdfyPanResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(idfy.IdfyRequest) error); ok {
		r1 = rf(idfyrequest)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ExtractPassport provides a mock function with given fields: idfyrequest
func (_m *Idfy) ExtractPassport(idfyrequest idfy.IdfyRequest) (*idfy.IdfyPassportResponse, error) {
	ret := _m.Called(idfyrequest)

	var r0 *idfy.IdfyPassportResponse
	if rf, ok := ret.Get(0).(func(idfy.IdfyRequest) *idfy.IdfyPassportResponse); ok {
		r0 = rf(idfyrequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*idfy.IdfyPassportResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(idfy.IdfyRequest) error); ok {
		r1 = rf(idfyrequest)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ExtractVoter provides a mock function with given fields: idfyrequest
func (_m *Idfy) ExtractVoter(idfyrequest idfy.IdfyRequest) (*idfy.IdfyVoterIdResponse, error) {
	ret := _m.Called(idfyrequest)

	var r0 *idfy.IdfyVoterIdResponse
	if rf, ok := ret.Get(0).(func(idfy.IdfyRequest) *idfy.IdfyVoterIdResponse); ok {
		r0 = rf(idfyrequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*idfy.IdfyVoterIdResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(idfy.IdfyRequest) error); ok {
		r1 = rf(idfyrequest)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FraudCheckAadhar provides a mock function with given fields: fraudCheckRequest
func (_m *Idfy) FraudCheckAadhar(fraudCheckRequest idfy.FraudCheckRequest) (*idfy.FraudCheckAadharResponse, error) {
	ret := _m.Called(fraudCheckRequest)

	var r0 *idfy.FraudCheckAadharResponse
	if rf, ok := ret.Get(0).(func(idfy.FraudCheckRequest) *idfy.FraudCheckAadharResponse); ok {
		r0 = rf(fraudCheckRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*idfy.FraudCheckAadharResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(idfy.FraudCheckRequest) error); ok {
		r1 = rf(fraudCheckRequest)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FraudCheckDl provides a mock function with given fields: fraudCheckRequest
func (_m *Idfy) FraudCheckDl(fraudCheckRequest idfy.FraudCheckRequest) (*idfy.FraudCheckDlResponse, error) {
	ret := _m.Called(fraudCheckRequest)

	var r0 *idfy.FraudCheckDlResponse
	if rf, ok := ret.Get(0).(func(idfy.FraudCheckRequest) *idfy.FraudCheckDlResponse); ok {
		r0 = rf(fraudCheckRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*idfy.FraudCheckDlResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(idfy.FraudCheckRequest) error); ok {
		r1 = rf(fraudCheckRequest)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FraudCheckPan provides a mock function with given fields: fraudCheckRequest
func (_m *Idfy) FraudCheckPan(fraudCheckRequest idfy.FraudCheckRequest) (*idfy.FraudCheckPanResponse, error) {
	ret := _m.Called(fraudCheckRequest)

	var r0 *idfy.FraudCheckPanResponse
	if rf, ok := ret.Get(0).(func(idfy.FraudCheckRequest) *idfy.FraudCheckPanResponse); ok {
		r0 = rf(fraudCheckRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*idfy.FraudCheckPanResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(idfy.FraudCheckRequest) error); ok {
		r1 = rf(fraudCheckRequest)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FraudCheckPassport provides a mock function with given fields: fraudCheckRequest
func (_m *Idfy) FraudCheckPassport(fraudCheckRequest idfy.FraudCheckRequest) (*idfy.FraudCheckPassportResponse, error) {
	ret := _m.Called(fraudCheckRequest)

	var r0 *idfy.FraudCheckPassportResponse
	if rf, ok := ret.Get(0).(func(idfy.FraudCheckRequest) *idfy.FraudCheckPassportResponse); ok {
		r0 = rf(fraudCheckRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*idfy.FraudCheckPassportResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(idfy.FraudCheckRequest) error); ok {
		r1 = rf(fraudCheckRequest)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FraudCheckVoter provides a mock function with given fields: fraudCheckRequest
func (_m *Idfy) FraudCheckVoter(fraudCheckRequest idfy.FraudCheckRequest) (*idfy.FraudCheckVoterResponse, error) {
	ret := _m.Called(fraudCheckRequest)

	var r0 *idfy.FraudCheckVoterResponse
	if rf, ok := ret.Get(0).(func(idfy.FraudCheckRequest) *idfy.FraudCheckVoterResponse); ok {
		r0 = rf(fraudCheckRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*idfy.FraudCheckVoterResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(idfy.FraudCheckRequest) error); ok {
		r1 = rf(fraudCheckRequest)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewIdfy interface {
	mock.TestingT
	Cleanup(func())
}

// NewIdfy creates a new instance of Idfy. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIdfy(t mockConstructorTestingTNewIdfy) *Idfy {
	mock := &Idfy{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
