// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IdfyConfig is an autogenerated mock type for the IdfyConfig type
type IdfyConfig struct {
	mock.Mock
}

// GetIdfyAccountId provides a mock function with given fields:
func (_m *IdfyConfig) GetIdfyAccountId() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetIdfyApiKey provides a mock function with given fields:
func (_m *IdfyConfig) GetIdfyApiKey() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetIdfyEndpoint provides a mock function with given fields:
func (_m *IdfyConfig) GetIdfyEndpoint() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetIdfyFraudCheckGetEndpoint provides a mock function with given fields:
func (_m *IdfyConfig) GetIdfyFraudCheckGetEndpoint() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetIdfyFraudCheckPostEndpoint provides a mock function with given fields:
func (_m *IdfyConfig) GetIdfyFraudCheckPostEndpoint() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

type mockConstructorTestingTNewIdfyConfig interface {
	mock.TestingT
	Cleanup(func())
}

// NewIdfyConfig creates a new instance of IdfyConfig. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIdfyConfig(t mockConstructorTestingTNewIdfyConfig) *IdfyConfig {
	mock := &IdfyConfig{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
