// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import (
	context "context"

	digilocker "bitbucket.org/junglee_games/getsetgo/sdks/digilocker"
	mock "github.com/stretchr/testify/mock"
)

// Digilocker is an autogenerated mock type for the Digilocker type
type Digilocker struct {
	mock.Mock
}

// CheckAccountstatus provides a mock function with given fields: ctx, mobile, aadhaar
func (_m *Digilocker) CheckAccountstatus(ctx context.Context, mobile string, aadhaar string) (*digilocker.AccountStatusDetails, error) {
	ret := _m.Called(ctx, mobile, aadhaar)

	var r0 *digilocker.AccountStatusDetails
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *digilocker.AccountStatusDetails); ok {
		r0 = rf(ctx, mobile, aadhaar)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*digilocker.AccountStatusDetails)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, mobile, aadhaar)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAddharDetails provides a mock function with given fields: ctx, transactionId, referenceId
func (_m *Digilocker) GetAddharDetails(ctx context.Context, transactionId string, referenceId string) (*digilocker.AadhaarDetails, error) {
	ret := _m.Called(ctx, transactionId, referenceId)

	var r0 *digilocker.AadhaarDetails
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *digilocker.AadhaarDetails); ok {
		r0 = rf(ctx, transactionId, referenceId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*digilocker.AadhaarDetails)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, transactionId, referenceId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRedirectURL provides a mock function with given fields: ctx
func (_m *Digilocker) GetRedirectURL(ctx context.Context) string {
	ret := _m.Called(ctx)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Healthcheck provides a mock function with given fields: ctx
func (_m *Digilocker) Healthcheck(ctx context.Context) (*digilocker.HealthcheckResult, error) {
	ret := _m.Called(ctx)

	var r0 *digilocker.HealthcheckResult
	if rf, ok := ret.Get(0).(func(context.Context) *digilocker.HealthcheckResult); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*digilocker.HealthcheckResult)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}


func (_m *Digilocker) GetPanDetails(ctx context.Context, refId string, panNumber string, fullName string) (*digilocker.PanDetails, error){
	return nil,nil
}

func ( m *Digilocker)GetPanDigilockerDoc(ctx context.Context, refId string) (*digilocker.PanDetails, error){
return nil,nil
}

// StartKYC provides a mock function with given fields: ctx, transactionId, referenceId, redirectURL
func (_m *Digilocker) StartKYC(ctx context.Context, transactionId string, referenceId string, redirectURL string) (*digilocker.KYCStartDetails, error) {
	ret := _m.Called(ctx, transactionId, referenceId, redirectURL)

	var r0 *digilocker.KYCStartDetails
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *digilocker.KYCStartDetails); ok {
		r0 = rf(ctx, transactionId, referenceId, redirectURL)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*digilocker.KYCStartDetails)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, transactionId, referenceId, redirectURL)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewDigilocker interface {
	mock.TestingT
	Cleanup(func())
}

// NewDigilocker creates a new instance of Digilocker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewDigilocker(t mockConstructorTestingTNewDigilocker) *Digilocker {
	mock := &Digilocker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
