package digilocker

const (
	//SAVERITY
	AVAILABLE                     = "AVAILABLE"
	POOR_AVAILABILITY             = "POOR_AVAILABILITY"
	PARTIALLY_AVAILABLE           = "PARTIALLY_AVAILABLE"
	SUFFICIENT_DATA_NOT_AVAILABLE = "SUFFICIENT_DATA_NOT_AVAILABLE"
	ERROR_PERFORMING_HEALTHCHECK  = "ERROR_PERFORMING_HEALTHCHECK"

	// newrelic metric constants
	HV_START_KYC_CALL         = "HV_START_KYC_CALL"
	HV_ACCOUNT_STATUS_CALL    = "HV_ACCOUNT_STATUS_CALL"
	HV_ADDHAR_DETAILS_CALL    = "HV_ADDHAR_DETAILS_CALL"
	HV_HEALTHCHECK_CALL       = "HV_HEALTHCHECK_CALL"
	HV_FETCH_PAN_DETAILS_CALL = "HV_FETCH_PAN_DETAILS_CALL"
)
